export default function Home() {
  return (
    <div className="p-4">
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
      <h1 className="text-2xl font-bold">欢迎使用图书管理系统</h1>
      <p className="text-muted-foreground">这里是主要内容区域</p>
    </div>
  );
}
